### ISSUE TITLE
Pictures are not added to AMLX file

### ISSUE THREAD

**Issue by mrentsch65** [TINF17C/ModellingWizard#4]
ComponentPicture, ComponentIcon and ManufacturerIcon are referenced via ExternalDataConnector, but not added to the AMLX package.

**Comment by DorianSnowball** [comment]
When trying to add a picture the following error occurs:
```
System.ArgumentException: Part URI cannot contain a Fragment component.
   at System.IO.Packaging.PackUriHelper.CreatePartUri(Uri partUri)
   at Aml.Editor.Plugin.MWData.CreateDevice(MWDevice device, Boolean isEdit)
   at Aml.Editor.Plugin.MWController.CreateDeviceOnClick(MWDevice newDevice, Boolean isEdit)
   at Aml.Editor.Plugin.CreateDevice.createDeviceBtn_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

```
